# OSEMN Exercises

### I am using jupyter-lab and I had to install a few packages in conda to use the widget magic, which allows me to have interactive plots for easier visualization. In case it doesn't work, please change the magic accordingly

In [1]:
%matplotlib widget
#%matplotlib inline

import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [2]:
random_list = np.random.random(100)
np.savetxt("simple_data.txt", random_list)

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [3]:
rng_matrix = np.random.random((5,5))
np.savetxt("data.txt", rng_matrix)

3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [4]:
the_matrix = np.loadtxt("data.txt")
np.savetxt("data.csv", the_matrix, delimiter = ",")

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [5]:
CC = pd.read_csv("credit_card.dat", header=None)

def credit_card_reader(number):
    credit_card = "" #set an empty string to append the digits to as strings.
    if len(number) == 118: #only run where the length of the binary string is 118 characters (114 bits + 4 bits padding)
        for n in range(int((len(number)-4)/6)):                #this range specification grants that n will range to 114/6 = 19, which is 16 (6-bit) digits plus 3 spaces. The -4 removes the padding at the end of each line.
            credit_card += chr(int(number[6*n:6*(n+1)],2))     #converts every 6 binary digits into the corresponding Unicode character, appends to the credit card.
    return credit_card

credit_cards = pd.DataFrame(CC[0].apply(credit_card_reader)) #applies the function to the 0-th column of the dataframe.
credit_cards = credit_cards.head(-1) #removes the last line of the dataframe which is just padding.
credit_cards = credit_cards.rename(columns = {0 : "Credit card number"}) #renames the column of the dataframe for fancier formatting
credit_cards.reset_index(drop = True) #resets the index counting for fancier formatting

     Credit card number
0   7648 5673 3775 2271
1   3257 8247 3354 2266
2   2722 0001 4011 6652
3   0661 3063 3742 3150
4   0432 1608 1462 4742
5   5827 2027 8785 7303
6   5774 8528 2087 1117
7   8140 1210 6352 2845
8   5764 1133 7301 7100
9   6456 1737 4126 6726
10  1228 8631 7382 0000
11  7051 0160 5374 3166
12  0618 3587 1630 6376
13  1545 5454 7444 5636
14  6735 3116 3202 6834
15  7287 5011 1547 8413
16  7033 2607 3328 4200
17  2568 5244 1874 5024
18  1684 2253 7570 7118
19  0672 2576 0575 6631
20  6332 8353 8787 1340
21  1813 3361 1175 4211
22  2477 6450 8840 2368
23  5512 3505 2563 1326
24  3083 7882 0621 0025
25  4521 5148 8045 0334
26  7563 3654 8713 5787
27  8324 2664 0476 5561
28  0565 2504 7168 3510
29  5107 5507 1767 0738
30  2462 1821 2448 1443
31  2788 0638 6861 6554
32  5851 5873 5474 0547
33  0670 1004 4013 2655
34  5874 5506 3048 0806
35  2805 5401 8462 1260
36  5083 8406 6310 1862
37  1076 1445 3013 2266
38  8440 4804 4844 5277
39  4758 6141 0686 1387
40  7586 0675 0315 2568
41  2544 1258 7432 5165
42  3474 5023 4434 5626
43  1410 0270 0434 5086
44  7315 4446 1104 4215
45  0224 7742 8300 0266
46  0170 2700 3145 0640
47  2006 2437 8054 1600
48  8142 4055 1776 0026
49  3026 7380 1241 1084

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

In [6]:
import json

path = "user_data.json"

with open(path) as infile:
    data = json.load(infile) #json.load() opens the file into a list data
    
    #each entry of data is a dictionary, so we keep the format by defining a dictionary that we will populate with lists of the entries as follows:
    
    types = {}
    
    types["ID"] = [i["ID"] for i in data if i["CreditCardType"]=="American Express"]
    types["JobTitle"] = [i["JobTitle"] for i in data if i["CreditCardType"]=="American Express"]
    types["EmailAddress"] = [i["EmailAddress"] for i in data if i["CreditCardType"]=="American Express"]
    types["FirstNameLastName"] = [i["FirstNameLastName"] for i in data if i["CreditCardType"]=="American Express"]
    types["CreditCard"] = [i["CreditCard"] for i in data if i["CreditCardType"]=="American Express"]
    types["CreditCardType"] = [i["CreditCardType"] for i in data if i["CreditCardType"]=="American Express"]
   
    #each types dictionary entry is a list of the elements that exist in data, for which the key CreditCardType is American Express.
    
    filtered_cards = np.array([types["ID"], types["JobTitle"], types["EmailAddress"], types["FirstNameLastName"], types["CreditCard"],types["CreditCardType"]], dtype = str).T
    
    #we create an array with each of the lists in the dictionary type. We transpose it for ease of readability, and to help with the formatting. This method foregoes the dictionary keys, but if that was important we prboably would have just left the file as a .json
    
    np.savetxt("filtered_cards.csv", filtered_cards, delimiter = ",", fmt = '%s')

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe what you see

In [7]:
import urllib.request
import matplotlib.pyplot as plt

url = 'https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1'
with urllib.request.urlopen(url) as data_file:
    data_mushrooms = pd.read_csv(data_file)
    
data_mushrooms

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,7,7,0,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,7,7,0,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,7,7,0,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,7,7,0,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,7,7,0,2,1,0,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,3,2,4,0,5,0,0,0,11,...,2,5,5,0,1,1,4,0,1,2
8120,0,5,2,4,0,5,0,0,0,11,...,2,5,5,0,0,1,4,0,4,2
8121,0,2,2,4,0,5,0,0,0,5,...,2,5,5,0,1,1,4,0,1,2
8122,1,3,3,4,0,8,1,0,1,0,...,1,7,7,0,2,1,0,7,4,2
8123,0,5,2,4,0,5,0,0,0,11,...,2,5,5,0,1,1,4,4,1,2

In [8]:
#Note: I am using the %matplotlib widget magic to allow interactive plots.


ones = data_mushrooms["class"][data_mushrooms["class"] == 1]
zeros = data_mushrooms["class"][data_mushrooms["class"] == 0]

#For the sake of nicer formatting, I am plotting a bar graph instead of a histogram, treating the data as categorical (since we only have two classes).

bar_graph = {"class 0": len(zeros), "class 1": len(ones)}
names = list(bar_graph.keys())
values = list(bar_graph.values())

fig = plt.figure()
plt.bar(names, values, color = ['blue', 'orange'])
plt.title("Class distribution of mushrooms")
fig.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

In [9]:
import urllib.request
import matplotlib.pyplot as plt

url = 'https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1'

with urllib.request.urlopen(url) as data_file:
    data = pd.read_csv(data_file)
data

,label,features_1,features_2,features_3,features_4,features_5,features_6,features_7,features_8,features_9,...,features_11,features_12,features_13,features_14,features_15,features_16,features_17,features_18,features_19,features_20
0,-89.243497,2.175170,-0.285786,-0.603396,-0.627453,-0.686474,0.381067,0.306205,-0.637447,-1.332087,...,1.290725,1.047483,-1.055467,0.853204,0.038665,-0.752959,0.577920,-0.657400,1.367308,0.570199
1,230.050125,1.481941,-1.327870,-0.543583,-0.303578,1.552964,0.549738,-0.763094,-0.455796,2.053388,...,-1.761306,-0.934284,-1.050999,0.444026,-0.037959,1.061624,-1.569870,2.410696,1.113594,2.329479
2,-286.844411,-1.154394,-0.178649,-1.636646,0.239353,-0.684994,0.587201,-0.209564,-0.428956,-0.757998,...,0.374645,-1.702189,-0.014514,-0.711557,-0.558523,-1.204526,0.234989,0.398384,-0.236555,0.642003
3,364.552862,0.197665,1.455707,1.562205,2.168207,0.053335,0.790492,-0.212023,-1.142483,-1.124906,...,0.712160,-2.844936,0.483994,-0.694294,1.349605,-1.303414,0.161987,0.754084,1.248258,-1.466045
4,515.460006,0.596676,0.969860,1.294158,-0.404728,2.145297,0.997481,-0.541670,-0.952850,-0.592084,...,-1.347072,0.243422,0.290336,0.798331,0.876428,-0.366807,-0.119534,0.892320,-0.806912,0.736080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,-328.100239,-1.820929,1.358539,-2.494838,0.828299,0.199255,0.142303,-0.582563,0.472356,-1.411304,...,-1.062502,2.299985,-0.085065,0.357165,-1.400150,-0.976176,-0.796009,-0.148662,0.978054,-0.804272
1996,-62.960036,-0.883712,-0.063687,-0.418704,-0.872601,0.363769,-0.368570,-0.104321,-2.493615,-1.694770,...,-0.197659,-0.533637,-0.598431,-0.039737,1.882953,-1.837356,0.583887,0.603931,-0.356482,0.029355
1997,-90.262252,-0.021394,-0.312864,-0.730848,-1.341482,-0.720862,-0.683872,-0.805370,-0.521334,-0.074645,...,1.899276,0.417949,0.324229,0.448252,-0.282110,-2.320763,1.484126,0.392324,-1.116838,-0.459027
1998,-74.333901,-0.041909,-0.862731,-1.232011,1.268843,0.093043,1.684069,0.753851,-0.537096,-0.971790,...,1.401321,-0.933149,-0.166864,1.152448,1.605114,-1.339651,0.105628,0.676177,-0.035598,-1.329490
1999,8.321454,-1.056364,0.259247,0.307835,1.094903,0.472395,1.702894,-1.981785,0.032232,-1.142503,...,0.370107,-1.574455,0.092401,0.249970,0.048932,-0.376273,1.285961,-0.054588,-1.183828,-0.356557

In [10]:
#Making a figure with six (3! for all the combos of the features) plot elements

fig, axs = plt.subplots(2,3, constrained_layout = True)

fig.suptitle("Plots of $features_1, features_2, features_3$")

features_1 = data["features_1"]
features_2 = data["features_2"]
features_3 = data["features_3"]

axs[0,0].scatter(features_1, features_2, c = features_3)
axs[0,0].set_xlabel("features_1")
axs[0,0].set_ylabel("features_2")
axs[0,0].set_title("coloring using features_3")

axs[0,1].scatter(features_1, features_3, c = features_2)
axs[0,1].set_xlabel("features_1")
axs[0,1].set_ylabel("features_3")
axs[0,1].set_title("coloring using features_2")

axs[0,2].scatter(features_2, features_1, c = features_3)
axs[0,2].set_xlabel("features_2")
axs[0,2].set_ylabel("features_1")
axs[0,2].set_title("coloring using features_3")

axs[1,0].scatter(features_2, features_3, c = features_1)
axs[1,0].set_xlabel("features_2")
axs[1,0].set_ylabel("features_3")
axs[1,0].set_title("coloring using features_1")

axs[1,1].scatter(features_3, features_1, c = features_2)
axs[1,1].set_xlabel("features_3")
axs[1,1].set_ylabel("features_1")
axs[1,1].set_title("coloring using features_2")

axs[1,2].scatter(features_3, features_2, c = features_1)
axs[1,2].set_xlabel("features_3")
axs[1,2].set_ylabel("features_2")
axs[1,2].set_title("coloring using features_1")
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

8\. Load the same file of point 6, and convert the file to json with Pandas.

In [11]:
#Pandas dataframes have a built-in method to convert a dataframe into a .json file. In the cell of exercise 6 the data is already imported into the dataframe data_mushrooms

data_mushrooms.to_json("mushroom_data.json")